export const GREETINGS = [
  "Hi!",
  "Hey!",
  "Heya!",
  "Hey there!",
  "How are things?",
  "What’s new?",
  "It’s good to see you.",
  "G’day!",
  "Howdy!",
  "What’s up?",
  "How’s it going?",
  "What’s happening?",
  "Yo!",
  "Hello!",
  "Hi there!",
];

export const FAREWELLS = [
  "Bye!",
  "Bye bye!",
  "See you later!",
  "See you soon!",
  "Talk to you later!",
  "Take it easy!",
  "Goodbye!",
  "Have a nice day!",
  "Have a good day!",
  "I look forward to our next meeting!",
  "Take care!",
  "It was nice to see you again!",
  "Goodnight!",
  "Catch you later!",
  "Peace out!",
  //   "bye",
  //   "bye bye",
  //   "see you later",
  //   "see you soon",
  //   "talk to you later",
  //   "ive got to get going",
  //   "i must be going",
  //   "ive got to get going, i have to wake up early tomorrow morning",
  //   "take it easy",
  //   "im off",
  //   "anyway,im off ive got a busy day tomorrow",
  //   "goodbye",
  //   "have a nice day",
  //   "i look forward to our next meeting",
  //   "take care",
  //   "it was nice to see you again",
  //   "it was nice seeing you",
  //   "good night",
  //   "later",
  //   "laters",
  //   "catch you later",
  //   "peace out",
  //   "im out of here",
  //   "i gotta jet",
  //   "gotta take off",
  //   "U gotta hit the road",
  //   "I gotta head out",
];

export const SMALL_TALK = [
  "Okay.",
  "Alrighty.",
  "Yup.",
  "Uh-huh.",
  "Hmmm.",
  "Alright.",
  "Mhmm.",
  "Yeah.",
];
